# Generated by Django 3.2.5 on 2021-07-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.CharField(default='https://www.youtube.com/channel/UCqwUrj10mAEsqezcItqvwEw', max_length=255),
        ),
    ]
